# Site settings
name: Dharmit Viradia
title: Dharmit Viradia | Graduate Student at Stevens Institute of Technology
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://dharmitviradia.me/
baseurl: ''
email: dviradia@stevens.edu
cover: https://dharmitviradia.me/img/og.png
logo: https://dharmitviradia.me/img/emojis/technologist.png
resume: https://dharmitviradia.me/resume.pdf
social:
  - title: email
    url: mailto:dviradia@stevens.edu
  - title: twitter
    url: https://twitter.com/DharmitViradia
  - title: instagram
    url: https://instagram.com/dharmit.viradia
  - title: facebook
    url: http://facebook.com/viradia.dharmit
  - title: github
    url: https://github.com/dharmitviradia
  - title: linkedin
    url: https://www.linkedin.com/in/dharmit-viradia/
